[package]
name = "mensa-app-backend"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Albers <usvan@student.kit.edu>", "Peer Booken <uglrl@student.kit.edu>", "Elena Häußler <uqhnu@student.kit.edu>", "Alexander Kutschera <ubsbo@student.kit.edu>", "Jonatan Ziegler <udslu@student.kit.edu"]
description = "Backend application for providing and synchronizing meal plan data of the canteens of the Studierendenwerk Karlsruhe."
repository = "https://github.com/kronos-et-al/MensaApp"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
chrono = "0.4.26"
thiserror = "1.0.40"
uuid = "1.4.0"
axum = {version = "0.6.18", features = ["http2", "macros"]}
async-graphql = {version = "5.0.10", features = ["chrono", "uuid", "tracing"]}
async-graphql-axum = "5.0.10"
tokio = {version = "1.29.0", features = ["full"]}
tracing = "0.1"
tracing-subscriber = {version = "0.2.0", features = ["env-filter"]}
base64 = "0.21.2"
sha2 = "0.10.7"
heck = "0.4.1"
reqwest = "0.11"
scraper = "0.17.1"
regex = "1.9.1"
futures = "0.3.28"
tokio-cron-scheduler = "0.9.4"
lettre = "0.10.4"
string_template = "0.2.1"
lazy_static = "1.4.0"


[dev-dependencies]
serde_json = "1.0"
serial_test = "2.0.0"
rand = "0.8.0"

[[bin]]
name = "graphql_mock"
path = "src/layer/trigger/graphql/bin.rs"
