[package]
name = "mensa-app-backend"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Albers <usvan@student.kit.edu>", "Peer Booken <uglrl@student.kit.edu>", "Elena Häußler <uqhnu@student.kit.edu>", "Alexander Kutschera <ubsbo@student.kit.edu>", "Jonatan Ziegler <udslu@student.kit.edu"]
description = "Backend application for providing and synchronizing meal plan data of the canteens of the Studierendenwerk Karlsruhe."
repository = "https://github.com/kronos-et-al/MensaApp"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
async-trait-with-sync = "0.1.36"
chrono = "0.4.26"

[dependencies.uuid]
version = "1.4.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]