name: Build-Android

on:
  push:
    branches: [ "main" ]
    paths: 
      - "app/**"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "backend/**"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run:  |
        cd app
        flutter pub get
    - run:  |
        cd app
        flutter test
    - run:  |
        cd app
        flutter build apk
