name: Build-Rust

on:
  push:
    branches: [ "main", "backend" ]
    paths: 
      - "backend/**"
  pull_request:
    branches: [ "main", "backend" ]
    paths: 
      - "backend/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - name: Check formating
      run: cargo fmt --check
    - name: Check linter warnings
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
